version: '3'
services:
  sphinx-doc:
    container_name: sphinx-doc
    image: tamatan/sphinx-latex:v20220316
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 8800:80
    volumes:
      - ./docs:/docs
      - ./debug:/debug
