services:
  sphinx-doc:
    container_name: sphinx-doc
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Tokyo
#    command: /bin/sh -c "while :; do sleep 10; done"
    ports:
      - 8800:80
    volumes:
      - ./docs:/docs
      - ./tmp:/tmp
      - ./debug:/debug
